version: '3.5'

services:
  backend:
    container_name: flaskbackend
    build: .
    image: flaskbackend:v1
    ports:
      - 5000:5000  
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports:
      - 1048:27017